### ISSUE TITLE
Static accessor mixin isn't properly transformed under certain circumstances

### ISSUE THREAD

**Issue by Johni0702** [FabricMC/Mixin#28] opened 2020-03-22 14:34 UTC
Applying [these changes](https://github.com/Johni0702/fabric-example-mod/commit/4ce4271ea8e3f26c424f3f8c902a6bc321b7a015) to fabric-example-mod, will cause the game (in intellij or with `./gradlew runClient`; haven't tested production environment) to crash with
```
java.lang.NoSuchMethodError: net.fabricmc.example.mixin.AccJsonGlProgram.getActiveProgram_$md$2f8dd9$0()Lnet/minecraft/client/gl/JsonGlProgram;
        at net.minecraft.client.gl.GlBlendState.handler$zdc001$init(GlBlendState.java:513)
        at net.minecraft.client.gl.GlBlendState.<init>(GlBlendState.java:30)
```
([full log](https://gist.github.com/Johni0702/5a8cc782dac87ee2ae1168d181122067))

Some observations:
- Explicitly loading `GlBlendState` (by uncommenting the line in `ExampleMod.java`) will make the issue disappear
- Explicitly loading `JsonGlProgram` similar to above observation makes no apparent difference
- It doesn't matter which method of `GlBlendState` is injected into (`<init>` is just better for demonstration than other ones because it gets called before you even enter a world)
- Injecting into `TitleScreen` (like the example mod does by default) instead of `GlBlendState` does not trigger the issue
- The first time I ran into this issue (when initially porting to fabric) I was using loader 0.6.3+build168 and MC 1.14.4 ([ref](https://github.com/Johni0702/BetterPortals/commit/f6fd27d464053e9a50e4c89d412498a423bb65ef#diff-392475fdf2bc320d17762ed97109a121R189-R191))
- Cannot reproduce with stock Mixin 0.8 and either Forge 1.14.4-28.1.70 (and manually updated eventbus 1.1.0 lib to fix another crash) or Forge 1.12.2-14.23.5.2838, hence why I'm posting here instead of upstream. Note that I didn't try to build a minimal example for those, so there may be something else (similar to observation 1) which caused it to not manifest.

**Comment by modmuss50** [comment] 2020-03-22 14:40
Is that when using stock mixin 0.8 on fabric?

**Comment by Johni0702** [comment] 2020-03-22 14:41
That's using whatever comes with Fabric (or rather, whatever the example mod is using).

**Comment by modmuss50** [comment] 2020-03-22 14:42
You mentioned you cannot reproduce it using stock mixin 0.8, did you try using stock mixin on fabric? Or was it another platform

**Comment by Johni0702** [comment] 2020-03-22 14:43
I did not try stock mixin 0.8 on fabric. I tried stock mixin 0.8 on modlauncher/forge (1.14.4) and on launchwrapper/forge (1.12.2).

**Comment by modmuss50** [comment] 2020-03-22 14:45
Ok, it may be worth trying. As that would help track down where the issue lies. I should have some time to look into shortly

**Comment by Johni0702** [comment] 2020-03-22 15:07
AFAICT stock mixin 0.8 on fabric is working fine as well.

Added these changes to the ones linked above:
```diff
diff --git a/build.gradle b/build.gradle
index f6220cc..31f8373 100644
--- a/build.gradle
+++ b/build.gradle
@@ -10,14 +10,22 @@ archivesBaseName = project.archives_base_name
 version = project.mod_version
 group = project.maven_group
 
+repositories {
+       maven {
+               url = "https://repo.spongepowered.org/maven/"
+       }
+}
+
 dependencies {
        //to change the versions see the gradle.properties file
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
-       modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
+       modImplementation("net.fabricmc:fabric-loader:${project.loader_version}") {
+               exclude group: "org.spongepowered", module: "mixin"
+       }
+       modImplementation "org.spongepowered:mixin:0.8"
 
        // Fabric API. This is technically optional, but you probably want it anyway.
-       modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
 
        // PSA: Some older mods, compiled on Loom 0.2.1, might have outdated Maven POMs.
        // You may need to force-disable transitiveness on them.
diff --git a/src/main/resources/fabric.mod.json b/src/main/resources/fabric.mod.json
index 197c798..90a66ad 100644
--- a/src/main/resources/fabric.mod.json
+++ b/src/main/resources/fabric.mod.json
@@ -28,7 +28,6 @@
 
   "depends": {
     "fabricloader": ">=0.7.4",
-    "fabric": "*",
     "minecraft": "1.15.x"
   },
   "suggests": {
```
Removed fabric-api because because some of its mixin depend on features not present in stock mixin.
With just that, I however ran into signature conflicts which I worked around by temporarily removing the signature from `.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8/dbe9e5db694a7c3cd644d5bb98f8a21295c75048/mixin-0.8.jar`.

**Comment by modmuss50** [comment] 2020-03-22 15:14
Ok, thats great. My assumption is these issues most likely came from a bad merge into our fork. Ill have to refresh my self on our changes, shouldnt be too hard to find by diffing our fork with upstream.

**Comment by modmuss50** [comment] 2020-07-09 21:15
Juat had this happen to me... humm

**Comment by Chocohead** [comment] 2020-07-09 22:41
If you start from the premise that stock Mixin does work as intended, which may or may not prove to be true more generally, [this](https://github.com/SpongePowered/Mixin/compare/master...FabricMC:fabric-0.8#diff-26e34647d1b0ed3ead39dba3a78dee78R777-R778) is probably the most suspicious difference we have. I've not walked through to see how much of a difference it makes at runtime, but it seems a fair place to start in terms of name mangling going wrong.

**Comment by modmuss50** [comment] 2020-07-16 23:13
Tracked it down to this commit: https://github.com/FabricMC/Mixin/commit/ec491e3b5d131b657bd095652f0d5195cd33a7cf

Reverting the 2 changes to findMethodInHierarchy fixed it, however im not sure if this re-introduces another bug.

**Comment by Earthcomputer** [comment] 2020-08-05 20:41
This just happened to me as well. Any chance we can get #33 merged?

**Closed** 2020-08-06 18:33 UTC
Labels: bug
